name: Test Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt

      - name: Run tests with coverage
        run: |
          coverage erase
          coverage run -m unittest discover -s tests
          coverage report > coverage.txt
          coverage html

      - name: Check coverage
        run: |
          coverage report --fail-under=90

      - name: Extract total coverage percentage
        id: extract_coverage
        run: |
          COVERAGE_PERCENT=$(grep 'TOTAL' coverage.txt | awk '{print $NF}' | sed 's/%//')
          if [ "$COVERAGE_PERCENT" -ge 80 ]; then
            EMOJI="😊"
          else
            EMOJI="😢"
          fi
          echo "coverage_percentage=${COVERAGE_PERCENT}%" >> $GITHUB_ENV
          echo "emoji=${EMOJI}" >> $GITHUB_ENV

      - name: Post coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Code Coverage Report
          message: |
            ### Code Coverage Report
            
            Total Coverage: ${{ env.coverage_percentage }} ${{ env.emoji }}
